     ##############################################################################
     ##############################################################################
     #### I initially made this for my server, the FloofNetwork, as nothing    ####
     #### like it exists. I decided to make it open source. You can help me    ####
     #### out by donating at paypal.me/TheFloofNetwork, or by checking out my  ####
     #### server, play.FloofNetwork.com.                                       ####
     ##############################################################################
     ##############################################################################


                          ################   #######       ####
                          ################   ########      ####
                          ####               #### ####     ####
                          ############       ####  ####    ####
                          ############       ####   ####   ####
                          ####               ####    ####  ####
                          ####               ####     #### ####
                          ####               ####      ########
                          ####               ####       #######


# Playtime is in hours. This is how long the person has to play before going to the group mentioned below this
playtime: 2

# Name of the group in LuckPerms. If you do not have LuckPerms, contact me on Discord, HaloFloof#2114,
# and I will edit it to be custom for you.
group: member


# Please o please do not change this.
version: 1.3